version: '3.8'

services:
  doko-kasse:
    image: hgebker/doko-kasse:main
    container_name: doko-kasse
    restart: unless-stopped
    ports:
     - '5000:5000'
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}

networks:
  default:
    external: true
    name: public-services
