version: '3.8'

services:
  doko-kasse:
    image: docker.io/hgebker/doko-kasse:main
    container_name: doko-kasse
    restart: unless-stopped
    ports:
     - '5000:5000'

networks:
  default:
    external: true
    name: public-services
