version: "3.8"

services:
  doko-kasse:
    image: hgebker/doko-kasse:v1.0.0
    container_name: doko-kasse
    restart: unless-stopped
    ports:
     - '5000:5000'
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}

  doko-kasse-int:
    image: hgebker/doko-kasse:main
    container_name: doko-kasse-int
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      MONGODB_URI: "mongodb://mongodb-dev:27017/dokokasse"

networks:
  default:
    name: doko-kasse
