services:
  filebrowser:
    container_name: filebrowser
    image: "filebrowser/filebrowser:latest"
    volumes:
      - /home/hgebk:/srv
      - /apps/filebrowser/database:/database
      - /apps/filebrowser/config:/config
    restart: unless-stopped
    ports:
      - "7333:80"
