services:
  mongodb-dev:
    container_name: mongodb-dev
    image: "mongo:4.4.18"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db

  mongodb-prod:
    container_name: mongodb-prod
    image: "mongo:4.4.18"
    ports:
      - "27007:27017"
    volumes:
      - mongo-data-dev:/data/db

volumes:
  mongo-data-dev:
  mongo-data-prod:
